services:
    mongo:
        image: mongo:7.0
        restart: always
        ports:
            - '27025:27017'
    mysql:
        image: percona:8.0
        restart: always
        ports:
            - '3315:3306'
        environment:
            - MYSQL_ROOT_PASSWORD=MYSQL_RANDOM_ROOT_PASSWORD
            - MYSQL_DATABASE=symfony_obuka_test
            - MYSQL_USER=symfony_obuka_app
            - MYSQL_PASSWORD=foobar

###> doctrine/doctrine-bundle ###
    database:
      image: postgres:${POSTGRES_VERSION:-16}-alpine
      environment:
        POSTGRES_DB: ${POSTGRES_DB:-app}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
        POSTGRES_USER: ${POSTGRES_USER:-app}
      healthcheck:
        test:
          - "CMD"
          - "pg_isready"
          - "-d"
          - "${POSTGRES_DB:-app}"
          - "-U"
          - "${POSTGRES_USER:-app}"
        timeout: 5s
        retries: 5
        start_period: 60s
      volumes:
        - database_data:/var/lib/postgresql/data:rw
###< doctrine/doctrine-bundle ###

volumes:
###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
