services:
    mongo:
        image: mongo:7.0
        restart: always
        ports:
            - '27025:27017'
    mysql:
        image: percona:8.0
        restart: always
        ports:
            - '3315:3306'
        environment:
            - MYSQL_ROOT_PASSWORD=MYSQL_RANDOM_ROOT_PASSWORD
            - MYSQL_DATABASE=symfony_obuka_test
            - MYSQL_USER=symfony_obuka_app
            - MYSQL_PASSWORD=foobar
